site_name: AleFire Library Wiki
docs_dir: docs

theme:
  name: material
  features:
    - navigation.path
    - content.code.copy
  palette:
    - scheme: default
      primary: red
      accent: amber
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: red
      accent: amber
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

plugins:
  - search
  - awesome-pages
  - mermaid2
  - i18n:
      docs_structure: suffix
      languages:
        - locale: it
          default: true
          name: Italiano
          build: true
        - locale: en
          default: false
          name: English
          build: true
